credentials:
  usernames:
    admin:
      email: admin@example.com
      first_name: Admin
      last_name: User
      password: $2b$12$As1n2XHLu33vcDPEuVBD/.AFdULDQwoEJR4X3sDNW25qrGGApuYwS
      roles: [admin]
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
    layla:
      email: layla@example.com
      first_name: Layla
      last_name: AI
      password: $2b$12$GRMItOZnMMnVUrTSjdMuSur6GePEBiqtUl6tWlickKt43Dqptu28q
      roles: [user]
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically

cookie:
  expiry_days: 30
  key: layla_analyzer_auth_key_v2_secure  # Enhanced security key
  name: layla_analyzer_cookie

# Pre-authorized emails for admin registration
pre-authorized:
  emails:
    - admin@yourcompany.com